import { chromium } from 'playwright';
import fs from 'node:fs';
const url=process.env.RADAR_TEST_URL || 'http://127.0.0.1:4173/';
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1600,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
await page.goto(url,{waitUntil:'networkidle',timeout:60000});
await page.getByRole('heading',{name:'Robinhood Mint Radar'}).waitFor();
await page.getByText('LIVE ECONOMIC SCAN').waitFor();
await page.getByText('MANUAL PACKAGES').waitFor();
const body=await page.locator('body').innerText();
if(body.includes('NaN')) throw new Error('NaN rendered');
if(!body.includes('Machine searches and verifies. Wallet execution stays manual.')) throw new Error('safety contract missing');
if(errors.length) throw new Error('browser console errors: '+errors.join(' | '));
fs.mkdirSync('proof',{recursive:true});
await page.screenshot({path:'proof/browser-1600x1000.png',fullPage:true});
fs.writeFileSync('proof/browser-smoke.json',JSON.stringify({url,title:await page.title(),ok:true,checked_at:new Date().toISOString()},null,2));
await browser.close();
console.log('browser smoke PASS',url);
